title: JABBADAFUNK
keywords: jabbadafunk, jabba da funk, freising, munich, funk, funkrock, rock, rap, music, deutschrap, band, rockband, livemusic, jimi hendrix, srni, livemusik, musik, bass, guitar, drums, vocals
description: jabba da funk - band from freising - rap funkrock music !

facebook: https://fb.com/jabbadafunk
spotify: https://open.spotify.com/album/4yVEkiFWnm4SmryiqMp31E?si=XpE94xX2SpKtJJuijMPzkg
youtube: https://www.youtube.com/watch?v=Qc6cF5pMobo
instagram: https://www.instagram.com/jabbadafunk/
downloads: https://drive.google.com/open?id=1Z1C5dEd_C4ySVIsR274a2mxOFUgYoQ8z

baseurl: /jabba

host: 0.0.0.0

exclude: [ "README.md", ".gitignore" ]
